server:
  port: 8082
spring:
  #  cloud:
  #    consul:
  #      host: localhost
  #      port: 8500
  application:
    name: service1
eureka:
  client:
    serviceUrl:
      defaultZone: http://erueka.talers.xyz/eureka/