server:
  port: 8082
spring:
  #  cloud:
  #    consul:
  #      host: localhost
  #      port: 8500
  application:
    name: service1
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/